version: '3.8'
services:
  db:
    container_name: mysql_container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_mysql_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - '6033:3306'
    volumes:
      - ./data:/var/lib/mysql